---
# Region and timezone selection

region: "America"
zone:   "Argentina/Buenos_Aires"

geoip:
    style: "json"
    url:   "https://ipapi.co/json"
    selector: "timezone"

# Use the system's zoneinfo for timezone data
adjustLiveTimezone: false
