---
# Disk partitioning module
# Offers: Erase Disk, Manual Partitioning, Replace Partition, Alongside

efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: "EFI"

userSwapChoices:
    - none
    - small       # RAM size up to 4GB
    - suspend     # RAM size (for hibernation)
    - file        # Swap file

drawNestedPartitions: false
alwaysShowPartitionLabels: true

defaultPartitionTableType: gpt

defaultFileSystemType: "ext4"

availableFileSystemTypes:
    - "ext4"
    - "btrfs"
    - "xfs"

# Enable LUKS encryption option
enableLuksAutomatedPartitioning: true
