---
# Services to enable/disable on the installed system

services:
    - name: "NetworkManager"
      mandatory: true

    - name: "systemd-timesyncd"
      mandatory: false

# Targets (multi-user = no GUI by default, user installs their own DE)
targets:
    - name: "multi-user"
      mandatory: true
