---
# shellprocess@cleanup
# Clean up installer artifacts from the installed system

dontChroot: false
timeout: 60

script:
    - command: "rm -rf /etc/calamares"
      name: "Removing installer files..."
    - command: "rm -f /etc/sudoers.d/g_wheel_nopasswd"
      name: "Cleaning up temporary sudo rules..."
