---
dontChroot: true
timeout: 60
verbose: true
script:
    - "-bash -c 'TARGET=$(find /tmp -maxdepth 1 -name calamares-root-* -type d | head -1); rm -rf $TARGET/etc/calamares; rm -f $TARGET/etc/sudoers.d/g_wheel_nopasswd'"
