---
# Check internet connectivity and minimum requirements
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true

# Require internet (needed for pacstrap)
internetCheckUrl: https://archlinux.org

requirements:
    requiredStorage:    8.0    # GB minimum
    requiredRam:        1.0    # GB minimum
    internetConnection: true
    check:
        - storage
        - ram
        - internet
        - root
    required:
        - storage
        - ram
        - internet
        - root

geoip:
    style: "json"
    url:   "https://ipapi.co/json"
    selector: "timezone"
