---
# ArchInstaller — Calamares settings.conf

modules-search: [ local, /usr/lib/calamares/modules ]

instances:
    - id: pacstrap
      module: shellprocess
      config: shellprocess@pacstrap.conf
    - id: post_install
      module: shellprocess
      config: shellprocess@post_install.conf
    - id: cleanup
      module: shellprocess
      config: shellprocess@cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - shellprocess@pacstrap
      - fstab
      - localecfg
      - networkcfg
      - hwclock
      - users
      - shellprocess@post_install
      - services-systemd
      - shellprocess@cleanup
      - umount
  - show:
      - finished

branding: archinstaller

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

quit-at-end: false
